### PR TITLE
Created bower.json file

### PR DESCRIPTION
**Pull request by cmacdonnacha**
Hey,

I created this [issue](https://github.com/nickaranz/slackapi-angularjs/issues/1) a while back and I decided to have a go at registering this package with bower. The first thing I need to do is create the `bower.json` file.

Once you accept this pull request I'll register it with bower and then anyone can simply run `bower install slackapi-angularjs --save-dev` to install this package.

Thanks,
Cathal.

### CODE REVIEW

**Comment by nickaranz** [comment]
Thanks Cathal. It's been a busy year. Request merged

**Comment by cmacdonnacha** [comment]
Good stuff. There are a few others changed to be made to the module itself so hopefully I'll get to commit those too. One thing, every time you merge back into `master` you'll have to re-build the `build` folder. Just wondering what you use to build it?

**Comment by cmacdonnacha** [comment]
Also, can you create a new version "0.1.0"? You can do this by clicking on [Releases](https://github.com/nickaranz/slackapi-angularjs/releases) and then selecting "Create new release" ( I don't have permissions to do this). This way the version will be picked up by bower. If you wish, you could add me as a collaborator and I can do this in the future instead of having to bother you. That's all up to you though. Thanks.

**Comment by cmacdonnacha** [comment]
Hey @nickaranz. I'm sure you're very busy but I was wondering if you could add me as a collaborator to this repo and I'll add the git tags so that people can download it via bower? I'm actually using this angualrjs service in a project of mine so I'd love to be able to just update it more regularly instead of having to bother you each time. Thanks,

**Comment by nickaranz** [comment]
Great idea ! You should have access in a bit. Thank you!

**Comment by cmacdonnacha** [comment]
Great, thanks!

**Pull request merged**
